{% set name = "ipymesh" %}
{% set version = "0.1.7" %}
{% set build = 1 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a6219449330fda67961b202bb3a7c0dbe2eb5449e64ea72f01b020546b634d5

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name }}

about:
  home: https://github.com/erdc/ipymesh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Custom Mesh Widget Library
  doc_url: https://github.com/erdc/ipymesh
  dev_url: https://github.com/erdc/ipymesh

extra:
  recipe-maintainers:
    - davidbrochart
